version: "3.9"
<<<<<<< HEAD
services:
  backend:
  db:
  frontend:
=======

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB_NAME=ufo_sightings
    depends_on:
      - db
>>>>>>> master
