# Generated by Django 3.2.7 on 2022-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20220731_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='created_by_user',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='description',
            field=models.CharField(default=None, max_length=1028),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='duration',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
