# Generated by Django 3.2.7 on 2022-08-01 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightings', '0003_auto_20220731_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufo_shape', models.CharField(choices=[('changing', 'Changing'), ('chevron', 'Chevron'), ('cigar', 'Cigar'), ('circle', 'Circle'), ('cone', 'Cone'), ('crescent', 'Crescent'), ('cross', 'Cross'), ('cylinder', 'Cylinder'), ('delta', 'Delta'), ('diamond', 'Diamond'), ('disk', 'Disk'), ('egg', 'Egg'), ('fireball', 'Fireball'), ('flash', 'Flash'), ('formation', 'Formation'), ('light', 'Light'), ('other', 'Other'), ('oval', 'Oval'), ('pyramid', 'Pyramid'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('sphere', 'Sphere'), ('teardrop', 'Teardrop'), ('triangle', 'Triangle'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('duration', models.CharField(default=None, max_length=32)),
                ('description', models.CharField(default=None, max_length=1028)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightings.sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, to='sightings.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
