# Generated by Django 3.2.15 on 2022-10-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20221003_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
